# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\35170\Desktop\+\Yangtze Uniersity\UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(919, 731)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/jixielogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("border-radius:7px")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setStatusTip("")
        self.gridWidget.setWhatsThis("")
        self.gridWidget.setAccessibleName("")
        self.gridWidget.setAccessibleDescription("")
        self.gridWidget.setStyleSheet("border-radius:7px;\n"
"background-color: rgb(255, 255, 255);")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_2.addWidget(self.gridWidget, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.main_widget.setObjectName("main_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_left = QtWidgets.QWidget(self.main_widget)
        self.widget_left.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_left.setMaximumSize(QtCore.QSize(99999, 16777215))
        self.widget_left.setStyleSheet("background-color: rgb(255, 217, 206);\n"
"border-top-left-radius:7px;\n"
"border-top-right-radius:7px;\n"
"border-bottom-left-radius:7px;\n"
"border-bottom-right-radius:7px;")
        self.widget_left.setObjectName("widget_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_left)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_logo = QtWidgets.QLabel(self.widget_left)
        self.label_logo.setMinimumSize(QtCore.QSize(0, 0))
        self.label_logo.setMaximumSize(QtCore.QSize(0, 0))
        self.label_logo.setStyleSheet("")
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.verticalLayout.addWidget(self.label_logo, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_person = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_person.setStyleSheet("QPushButton{\n"
"\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:0px;\n"
"    color: rgb(143, 213, 238);\n"
"\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/person.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_person.setIcon(icon1)
        self.pushButton_person.setCheckable(True)
        self.pushButton_person.setAutoExclusive(True)
        self.pushButton_person.setObjectName("pushButton_person")
        self.verticalLayout.addWidget(self.pushButton_person)
        self.pushButton_home = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_home.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_home.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/zero.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_home.setIcon(icon2)
        self.pushButton_home.setCheckable(True)
        self.pushButton_home.setAutoExclusive(True)
        self.pushButton_home.setObjectName("pushButton_home")
        self.verticalLayout.addWidget(self.pushButton_home)
        self.pushButton_dianjing = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_dianjing.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_dianjing.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/game.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_dianjing.setIcon(icon3)
        self.pushButton_dianjing.setCheckable(True)
        self.pushButton_dianjing.setAutoExclusive(True)
        self.pushButton_dianjing.setObjectName("pushButton_dianjing")
        self.verticalLayout.addWidget(self.pushButton_dianjing)
        self.pushButton_bangong = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_bangong.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_bangong.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/work.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_bangong.setIcon(icon4)
        self.pushButton_bangong.setCheckable(True)
        self.pushButton_bangong.setAutoExclusive(True)
        self.pushButton_bangong.setObjectName("pushButton_bangong")
        self.verticalLayout.addWidget(self.pushButton_bangong)
        self.pushButton_ps = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_ps.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_ps.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/adobe photoshop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ps.setIcon(icon5)
        self.pushButton_ps.setCheckable(True)
        self.pushButton_ps.setAutoExclusive(True)
        self.pushButton_ps.setObjectName("pushButton_ps")
        self.verticalLayout.addWidget(self.pushButton_ps)
        self.pushButton_jianying = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_jianying.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_jianying.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_jianying.setIcon(icon6)
        self.pushButton_jianying.setCheckable(True)
        self.pushButton_jianying.setAutoExclusive(True)
        self.pushButton_jianying.setObjectName("pushButton_jianying")
        self.verticalLayout.addWidget(self.pushButton_jianying)
        self.pushButton_yingjian = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_yingjian.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_yingjian.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/chip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_yingjian.setIcon(icon7)
        self.pushButton_yingjian.setCheckable(True)
        self.pushButton_yingjian.setAutoExclusive(True)
        self.pushButton_yingjian.setObjectName("pushButton_yingjian")
        self.verticalLayout.addWidget(self.pushButton_yingjian)
        self.pushButton_xinmeiti = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_xinmeiti.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_xinmeiti.setFont(font)
        self.pushButton_xinmeiti.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_xinmeiti.setIcon(icon8)
        self.pushButton_xinmeiti.setCheckable(True)
        self.pushButton_xinmeiti.setAutoExclusive(True)
        self.pushButton_xinmeiti.setObjectName("pushButton_xinmeiti")
        self.verticalLayout.addWidget(self.pushButton_xinmeiti)
        self.pushButton_net = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_net.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_net.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_net.setIcon(icon9)
        self.pushButton_net.setCheckable(True)
        self.pushButton_net.setAutoExclusive(True)
        self.pushButton_net.setObjectName("pushButton_net")
        self.verticalLayout.addWidget(self.pushButton_net)
        self.pushButton_code = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_code.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_code.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/code.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_code.setIcon(icon10)
        self.pushButton_code.setCheckable(True)
        self.pushButton_code.setAutoExclusive(True)
        self.pushButton_code.setObjectName("pushButton_code")
        self.verticalLayout.addWidget(self.pushButton_code)
        self.pushButton_yidong = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_yidong.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_yidong.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_yidong.setIcon(icon11)
        self.pushButton_yidong.setCheckable(True)
        self.pushButton_yidong.setAutoExclusive(True)
        self.pushButton_yidong.setObjectName("pushButton_yidong")
        self.verticalLayout.addWidget(self.pushButton_yidong)
        self.pushButton_jianyi = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_jianyi.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_jianyi.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/suggest.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_jianyi.setIcon(icon12)
        self.pushButton_jianyi.setCheckable(True)
        self.pushButton_jianyi.setAutoExclusive(True)
        self.pushButton_jianyi.setObjectName("pushButton_jianyi")
        self.verticalLayout.addWidget(self.pushButton_jianyi)
        self.pushButton_setting = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_setting.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_setting.setFont(font)
        self.pushButton_setting.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting.setIcon(icon13)
        self.pushButton_setting.setCheckable(True)
        self.pushButton_setting.setAutoExclusive(True)
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.verticalLayout.addWidget(self.pushButton_setting)
        self.pushButton_tools = QtWidgets.QPushButton(self.widget_left)
        self.pushButton_tools.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_tools.setFont(font)
        self.pushButton_tools.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 217, 206);\n"
"    border-radius:3px;\n"
"    border:0px;\n"
"    color:rgb(89,83,88);\n"
"    text-align:left;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(153, 193, 185);\n"
"    border-radius:3px;\n"
"}\n"
"QPushButton:pressed{\n"
"    border:2px solid rgb(0, 0, 0);\n"
"\n"
"\n"
"}\n"
"QPushButton:checked{\n"
"    border-radius:0px;\n"
"    border-left:5px solid rgb(142, 125, 190);\n"
"    \n"
"\n"
"    color:rgb(85, 85, 255);\n"
"}\n"
"\n"
"")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_tools.setIcon(icon14)
        self.pushButton_tools.setCheckable(True)
        self.pushButton_tools.setAutoExclusive(True)
        self.pushButton_tools.setObjectName("pushButton_tools")
        self.verticalLayout.addWidget(self.pushButton_tools)
        self.gridLayout.addWidget(self.widget_left, 0, 0, 7, 1)
        self.widget_top = QtWidgets.QWidget(self.main_widget)
        self.widget_top.setMaximumSize(QtCore.QSize(16777215, 30))
        self.widget_top.setStyleSheet("background-color: rgb(142, 125, 190);\n"
"border-top-right-radius:7px;\n"
"")
        self.widget_top.setObjectName("widget_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_top)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_name = QtWidgets.QLabel(self.widget_top)
        self.label_name.setMaximumSize(QtCore.QSize(600, 16777215))
        self.label_name.setAutoFillBackground(False)
        self.label_name.setStyleSheet("")
        self.label_name.setObjectName("label_name")
        self.horizontalLayout.addWidget(self.label_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_min = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_min.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton_min.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_min.setStyleSheet("QPushButton{\n"
"border-image:url(\"image/min.png\")\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(172, 172, 172);\n"
"border-radius:7px;\n"
"}")
        self.pushButton_min.setText("")
        self.pushButton_min.setObjectName("pushButton_min")
        self.horizontalLayout.addWidget(self.pushButton_min, 0, QtCore.Qt.AlignVCenter)
        self.pushButton_close = QtWidgets.QPushButton(self.widget_top)
        self.pushButton_close.setMinimumSize(QtCore.QSize(15, 15))
        self.pushButton_close.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_close.setStyleSheet("QPushButton{\n"
"border-image:url(\"image/close.png\")\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(172, 172, 172);\n"
"border-radius:7px;\n"
"}")
        self.pushButton_close.setText("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close, 0, QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.widget_top, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.stackedWidget_right = QtWidgets.QStackedWidget(self.main_widget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.stackedWidget_right.setFont(font)
        self.stackedWidget_right.setStyleSheet("QStackedWidget{\n"
"\n"
"border-bottom-right-radius:7px;\n"
"\n"
"}")
        self.stackedWidget_right.setObjectName("stackedWidget_right")
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.page1)
        self.comboBox_3.setMouseTracking(False)
        self.comboBox_3.setStyleSheet("QComboBox{\n"
"    \n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"     border :  0px  solid  gray ;\n"
"     \n"
"     padding :  1px  2px  1px  2px ; \n"
"     min-width :  3em ;  \n"
"}\n"
"QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol- position :  top  right ;\n"
"     width :  20px ;\n"
" \n"
"     border-left-width :  1px ;\n"
"     /*border-left-color : darkgray;*/\n"
"     border-left-style :  solid ;  /* just a single line */\n"
"     border-top-right-radius:  3px ;  /* same radius as the QComboBox */\n"
"     border-bottom-right-radius:  3px ;\n"
"}\n"
" \n"
"QComboBox::down-arrow {\n"
"     border-image:url(\"image/down.png\");\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_3, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_reload = QtWidgets.QPushButton(self.page1)
        self.pushButton_reload.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:5px;\n"
"\n"
"    background-color: rgb(185, 185, 185);\n"
"}")
        self.pushButton_reload.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_reload.setIcon(icon15)
        self.pushButton_reload.setObjectName("pushButton_reload")
        self.gridLayout_3.addWidget(self.pushButton_reload, 0, 5, 1, 1)
        self.pushButton_left = QtWidgets.QPushButton(self.page1)
        self.pushButton_left.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:5px;\n"
"\n"
"    background-color: rgb(185, 185, 185);\n"
"}")
        self.pushButton_left.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_left.setIcon(icon16)
        self.pushButton_left.setObjectName("pushButton_left")
        self.gridLayout_3.addWidget(self.pushButton_left, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 3, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.page1)
        self.comboBox_1.setMouseTracking(False)
        self.comboBox_1.setStyleSheet("QComboBox{\n"
"    \n"
"    \n"
"\n"
"     border :  0px  solid  gray ;\n"
"     \n"
"    background-color: rgb(255, 255, 255);\n"
"     padding :  1px  2px  1px  2px ; \n"
"     min-width :  3em ;  \n"
"}\n"
"QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol- position :  top  right ;\n"
"     width :  20px ;\n"
" \n"
"     border-left-width :  1px ;\n"
"     /*border-left-color : darkgray;*/\n"
"     border-left-style :  solid ;  /* just a single line */\n"
"     border-top-right-radius:  3px ;  /* same radius as the QComboBox */\n"
"     border-bottom-right-radius:  3px ;\n"
"}\n"
" \n"
"QComboBox::down-arrow {\n"
"     border-image:url(\"image/down.png\");\n"
"}")
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton_right = QtWidgets.QPushButton(self.page1)
        self.pushButton_right.setStyleSheet("QPushButton{\n"
"border:0px;\n"
"}\n"
"QPushButton:hover{\n"
"border-radius:5px;\n"
"\n"
"    background-color: rgb(185, 185, 185);\n"
"}")
        self.pushButton_right.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("c:\\Users\\35170\\Desktop\\+\\Yangtze Uniersity\\image/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_right.setIcon(icon17)
        self.pushButton_right.setObjectName("pushButton_right")
        self.gridLayout_3.addWidget(self.pushButton_right, 0, 6, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.page1)
        self.comboBox_2.setMouseTracking(False)
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"\n"
"     border :  0px  solid  gray ;\n"
"     \n"
"    background-color: rgb(255, 255, 255);\n"
"     padding :  1px  2px  1px  2px ; \n"
"     min-width :  3em ;  \n"
"}\n"
"QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol- position :  top  right ;\n"
"     width :  20px ;\n"
" \n"
"     border-left-width :  1px ;\n"
"     /*border-left-color : darkgray;*/\n"
"     border-left-style :  solid ;  /* just a single line */\n"
"     border-top-right-radius:  3px ;  /* same radius as the QComboBox */\n"
"     border-bottom-right-radius:  3px ;\n"
"}\n"
" \n"
"QComboBox::down-arrow {\n"
"     border-image:url(\"image/down.png\");\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.page1)
        self.webEngineView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.webEngineView.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.webEngineView.setProperty("url", QtCore.QUrl("https://mp.weixin.qq.com/s/N3uN1a2lxzfJb5yOsKTw9g"))
        self.webEngineView.setObjectName("webEngineView")
        self.gridLayout_3.addWidget(self.webEngineView, 2, 0, 1, 7)
        self.stackedWidget_right.addWidget(self.page1)
        self.page_dianjin = QtWidgets.QWidget()
        self.page_dianjin.setObjectName("page_dianjin")
        self.label = QtWidgets.QLabel(self.page_dianjin)
        self.label.setGeometry(QtCore.QRect(350, 350, 108, 24))
        self.label.setObjectName("label")
        self.stackedWidget_right.addWidget(self.page_dianjin)
        self.page_bangong = QtWidgets.QWidget()
        self.page_bangong.setObjectName("page_bangong")
        self.label_2 = QtWidgets.QLabel(self.page_bangong)
        self.label_2.setGeometry(QtCore.QRect(360, 200, 191, 71))
        self.label_2.setStyleSheet("font: 75 36pt \"微软雅黑\";")
        self.label_2.setObjectName("label_2")
        self.stackedWidget_right.addWidget(self.page_bangong)
        self.page_ps = QtWidgets.QWidget()
        self.page_ps.setObjectName("page_ps")
        self.label_3 = QtWidgets.QLabel(self.page_ps)
        self.label_3.setGeometry(QtCore.QRect(240, 200, 261, 221))
        self.label_3.setStyleSheet("font: 75 36pt \"微软雅黑\";")
        self.label_3.setObjectName("label_3")
        self.stackedWidget_right.addWidget(self.page_ps)
        self.page_jianyin = QtWidgets.QWidget()
        self.page_jianyin.setObjectName("page_jianyin")
        self.label_4 = QtWidgets.QLabel(self.page_jianyin)
        self.label_4.setGeometry(QtCore.QRect(260, 190, 191, 71))
        self.label_4.setStyleSheet("font: 75 36pt \"微软雅黑\";")
        self.label_4.setObjectName("label_4")
        self.stackedWidget_right.addWidget(self.page_jianyin)
        self.page_yingjian = QtWidgets.QWidget()
        self.page_yingjian.setObjectName("page_yingjian")
        self.label_5 = QtWidgets.QLabel(self.page_yingjian)
        self.label_5.setGeometry(QtCore.QRect(250, 210, 191, 71))
        self.label_5.setStyleSheet("font: 75 36pt \"微软雅黑\";")
        self.label_5.setObjectName("label_5")
        self.stackedWidget_right.addWidget(self.page_yingjian)
        self.page_meiti = QtWidgets.QWidget()
        self.page_meiti.setObjectName("page_meiti")
        self.label_6 = QtWidgets.QLabel(self.page_meiti)
        self.label_6.setGeometry(QtCore.QRect(240, 220, 191, 71))
        self.label_6.setStyleSheet("font: 75 36pt \"微软雅黑\";")
        self.label_6.setObjectName("label_6")
        self.stackedWidget_right.addWidget(self.page_meiti)
        self.page_net = QtWidgets.QWidget()
        self.page_net.setObjectName("page_net")
        self.label_65 = QtWidgets.QLabel(self.page_net)
        self.label_65.setGeometry(QtCore.QRect(360, 330, 191, 71))
        self.label_65.setStyleSheet("font: 75 36pt \"微软雅黑\";")
        self.label_65.setObjectName("label_65")
        self.stackedWidget_right.addWidget(self.page_net)
        self.page_code = QtWidgets.QWidget()
        self.page_code.setObjectName("page_code")
        self.label_7 = QtWidgets.QLabel(self.page_code)
        self.label_7.setGeometry(QtCore.QRect(270, 290, 191, 71))
        self.label_7.setStyleSheet("font: 75 36pt \"微软雅黑\";")
        self.label_7.setObjectName("label_7")
        self.listWidget = QtWidgets.QListWidget(self.page_code)
        self.listWidget.setGeometry(QtCore.QRect(60, 140, 256, 192))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.stackedWidget_right.addWidget(self.page_code)
        self.page_mobile = QtWidgets.QWidget()
        self.page_mobile.setObjectName("page_mobile")
        self.label_8 = QtWidgets.QLabel(self.page_mobile)
        self.label_8.setGeometry(QtCore.QRect(220, 250, 191, 71))
        self.label_8.setStyleSheet("font: 75 36pt \"微软雅黑\";")
        self.label_8.setObjectName("label_8")
        self.stackedWidget_right.addWidget(self.page_mobile)
        self.page_suggest = QtWidgets.QWidget()
        self.page_suggest.setObjectName("page_suggest")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.page_suggest)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.stackedWidget_right.addWidget(self.page_suggest)
        self.page_setting = QtWidgets.QWidget()
        self.page_setting.setObjectName("page_setting")
        self.checkBox_ui = QtWidgets.QCheckBox(self.page_setting)
        self.checkBox_ui.setGeometry(QtCore.QRect(180, 170, 91, 16))
        self.checkBox_ui.setObjectName("checkBox_ui")
        self.stackedWidget_right.addWidget(self.page_setting)
        self.page_tools = QtWidgets.QWidget()
        self.page_tools.setObjectName("page_tools")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.page_tools)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 150, 198, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_warning = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_warning.setObjectName("pushButton_warning")
        self.horizontalLayout_3.addWidget(self.pushButton_warning)
        self.pushButton_loginweb = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_loginweb.setObjectName("pushButton_loginweb")
        self.horizontalLayout_3.addWidget(self.pushButton_loginweb)
        self.stackedWidget_right.addWidget(self.page_tools)
        self.page_person = QtWidgets.QWidget()
        self.page_person.setStyleSheet("")
        self.page_person.setObjectName("page_person")
        self.label_user = QtWidgets.QLabel(self.page_person)
        self.label_user.setGeometry(QtCore.QRect(10, -20, 191, 71))
        self.label_user.setStyleSheet("")
        self.label_user.setObjectName("label_user")
        self.label_logo_2 = QtWidgets.QLabel(self.page_person)
        self.label_logo_2.setGeometry(QtCore.QRect(20, 30, 100, 100))
        self.label_logo_2.setMinimumSize(QtCore.QSize(80, 80))
        self.label_logo_2.setMaximumSize(QtCore.QSize(100, 100))
        self.label_logo_2.setStyleSheet("")
        self.label_logo_2.setText("")
        self.label_logo_2.setObjectName("label_logo_2")
        self.label_username = QtWidgets.QLabel(self.page_person)
        self.label_username.setGeometry(QtCore.QRect(140, 40, 81, 21))
        self.label_username.setStyleSheet("")
        self.label_username.setObjectName("label_username")
        self.label_emailcode = QtWidgets.QLabel(self.page_person)
        self.label_emailcode.setGeometry(QtCore.QRect(140, 70, 141, 16))
        self.label_emailcode.setStyleSheet("")
        self.label_emailcode.setObjectName("label_emailcode")
        self.label_userjob = QtWidgets.QLabel(self.page_person)
        self.label_userjob.setGeometry(QtCore.QRect(140, 100, 141, 16))
        self.label_userjob.setStyleSheet("\n"
"color:rgb(0, 0, 255)")
        self.label_userjob.setObjectName("label_userjob")
        self.stackedWidget = QtWidgets.QStackedWidget(self.page_person)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QtCore.QRect(430, 80, 361, 451))
        self.stackedWidget.setStyleSheet("border-radius:7px;\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgb(142, 249, 243);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_massage = QtWidgets.QWidget()
        self.page_massage.setObjectName("page_massage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_massage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_QQ = QtWidgets.QLabel(self.page_massage)
        self.label_QQ.setObjectName("label_QQ")
        self.verticalLayout_3.addWidget(self.label_QQ)
        self.label_QQnum = QtWidgets.QLabel(self.page_massage)
        self.label_QQnum.setObjectName("label_QQnum")
        self.verticalLayout_3.addWidget(self.label_QQnum)
        self.label_phone = QtWidgets.QLabel(self.page_massage)
        self.label_phone.setObjectName("label_phone")
        self.verticalLayout_3.addWidget(self.label_phone)
        self.label_phonenum = QtWidgets.QLabel(self.page_massage)
        self.label_phonenum.setObjectName("label_phonenum")
        self.verticalLayout_3.addWidget(self.label_phonenum)
        self.label_Email = QtWidgets.QLabel(self.page_massage)
        self.label_Email.setObjectName("label_Email")
        self.verticalLayout_3.addWidget(self.label_Email)
        self.label_Emailnum = QtWidgets.QLabel(self.page_massage)
        self.label_Emailnum.setObjectName("label_Emailnum")
        self.verticalLayout_3.addWidget(self.label_Emailnum)
        self.label_Name = QtWidgets.QLabel(self.page_massage)
        self.label_Name.setObjectName("label_Name")
        self.verticalLayout_3.addWidget(self.label_Name)
        self.label_Namenum = QtWidgets.QLabel(self.page_massage)
        self.label_Namenum.setObjectName("label_Namenum")
        self.verticalLayout_3.addWidget(self.label_Namenum)
        self.label_Code = QtWidgets.QLabel(self.page_massage)
        self.label_Code.setObjectName("label_Code")
        self.verticalLayout_3.addWidget(self.label_Code)
        self.label_Codenum = QtWidgets.QLabel(self.page_massage)
        self.label_Codenum.setObjectName("label_Codenum")
        self.verticalLayout_3.addWidget(self.label_Codenum)
        self.label_School = QtWidgets.QLabel(self.page_massage)
        self.label_School.setObjectName("label_School")
        self.verticalLayout_3.addWidget(self.label_School)
        self.label_Schoolnum = QtWidgets.QLabel(self.page_massage)
        self.label_Schoolnum.setObjectName("label_Schoolnum")
        self.verticalLayout_3.addWidget(self.label_Schoolnum)
        self.label_zhu = QtWidgets.QLabel(self.page_massage)
        self.label_zhu.setObjectName("label_zhu")
        self.verticalLayout_3.addWidget(self.label_zhu)
        self.stackedWidget.addWidget(self.page_massage)
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_login)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.lineEdit_account = QtWidgets.QLineEdit(self.page_login)
        self.lineEdit_account.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_account.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_account.setStyleSheet("")
        self.lineEdit_account.setInputMask("")
        self.lineEdit_account.setText("")
        self.lineEdit_account.setMaxLength(32765)
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.verticalLayout_6.addWidget(self.lineEdit_account, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_password = QtWidgets.QLineEdit(self.page_login)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_password.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_password.setStyleSheet("")
        self.lineEdit_password.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout_6.addWidget(self.lineEdit_password, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_login_2 = QtWidgets.QPushButton(self.page_login)
        self.pushButton_login_2.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_login_2.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_login_2.setStyleSheet("QPushButton{\n"
"border-radius:3px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background:rgb(222, 222, 222);\n"
"\n"
"border:1px solid rgb(191, 191, 191);\n"
"}")
        self.pushButton_login_2.setObjectName("pushButton_login_2")
        self.verticalLayout_6.addWidget(self.pushButton_login_2, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_enrool = QtWidgets.QPushButton(self.page_login)
        self.pushButton_enrool.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_enrool.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_enrool.setStyleSheet("QPushButton{\n"
"border-radius:3px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background:rgb(222, 222, 222);\n"
"\n"
"border:1px solid rgb(191, 191, 191);\n"
"}")
        self.pushButton_enrool.setObjectName("pushButton_enrool")
        self.verticalLayout_6.addWidget(self.pushButton_enrool, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.page_login)
        self.page_enrool = QtWidgets.QWidget()
        self.page_enrool.setObjectName("page_enrool")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_enrool)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 5, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 1, 0, 1, 1)
        self.pushButton_backlogin = QtWidgets.QPushButton(self.page_enrool)
        self.pushButton_backlogin.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_backlogin.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_backlogin.setStyleSheet("QPushButton{\n"
"border-radius:3px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background:rgb(222, 222, 222);\n"
"\n"
"border:1px solid rgb(191, 191, 191);\n"
"}")
        self.pushButton_backlogin.setObjectName("pushButton_backlogin")
        self.gridLayout_6.addWidget(self.pushButton_backlogin, 4, 1, 1, 1)
        self.lineEdit_phone = QtWidgets.QLineEdit(self.page_enrool)
        self.lineEdit_phone.setMinimumSize(QtCore.QSize(200, 30))
        self.lineEdit_phone.setMaximumSize(QtCore.QSize(200, 30))
        self.lineEdit_phone.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit_phone.setStyleSheet("")
        self.lineEdit_phone.setInputMask("")
        self.lineEdit_phone.setText("")
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.gridLayout_6.addWidget(self.lineEdit_phone, 2, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.pushButton_login = QtWidgets.QPushButton(self.page_enrool)
        self.pushButton_login.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton_login.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton_login.setStyleSheet("QPushButton{\n"
"border-radius:3px;\n"
"border:1px solid rgb(222, 222, 222);\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background:rgb(222, 222, 222);\n"
"\n"
"border:1px solid rgb(191, 191, 191);\n"
"}")
        self.pushButton_login.setObjectName("pushButton_login")
        self.gridLayout_6.addWidget(self.pushButton_login, 4, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem7, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_enrool)
        self.page_login_select = QtWidgets.QWidget()
        self.page_login_select.setObjectName("page_login_select")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_login_select)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.webEngineView_shua = QtWebEngineWidgets.QWebEngineView(self.page_login_select)
        self.webEngineView_shua.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.webEngineView_shua.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.webEngineView_shua.setProperty("url", QtCore.QUrl("https://mp.weixin.qq.com/s/N3uN1a2lxzfJb5yOsKTw9g"))
        self.webEngineView_shua.setObjectName("webEngineView_shua")
        self.verticalLayout_4.addWidget(self.webEngineView_shua)
        self.stackedWidget.addWidget(self.page_login_select)
        self.page_job = QtWidgets.QWidget()
        self.page_job.setObjectName("page_job")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_job)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.label_74 = QtWidgets.QLabel(self.page_job)
        self.label_74.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_74.setStyleSheet("font: 75 14pt \"微软雅黑\";\n"
"color: rgb(255, 241, 85);")
        self.label_74.setObjectName("label_74")
        self.verticalLayout_5.addWidget(self.label_74, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_22 = QtWidgets.QPushButton(self.page_job)
        self.pushButton_22.setMinimumSize(QtCore.QSize(200, 30))
        self.pushButton_22.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButton_22.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_5.addWidget(self.pushButton_22, 0, QtCore.Qt.AlignHCenter)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.stackedWidget.addWidget(self.page_job)
        self.label_daytxt = QtWidgets.QLabel(self.page_person)
        self.label_daytxt.setGeometry(QtCore.QRect(80, 6, 551, 21))
        self.label_daytxt.setStyleSheet("")
        self.label_daytxt.setText("")
        self.label_daytxt.setObjectName("label_daytxt")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_person)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-40, 150, 471, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.stackedWidget_right.addWidget(self.page_person)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget_right.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget_right, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.main_widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_right.setCurrentIndex(13)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "长大计协"))
        self.pushButton_person.setText(_translate("MainWindow", "用户"))
        self.pushButton_home.setText(_translate("MainWindow", " 主 页"))
        self.pushButton_dianjing.setText(_translate("MainWindow", "电竞部"))
        self.pushButton_bangong.setText(_translate("MainWindow", "办公部"))
        self.pushButton_ps.setText(_translate("MainWindow", "P S 部"))
        self.pushButton_jianying.setText(_translate("MainWindow", "剪映部"))
        self.pushButton_yingjian.setText(_translate("MainWindow", "硬件部"))
        self.pushButton_xinmeiti.setText(_translate("MainWindow", "新媒体"))
        self.pushButton_net.setText(_translate("MainWindow", "网站部"))
        self.pushButton_code.setText(_translate("MainWindow", "编程部"))
        self.pushButton_yidong.setText(_translate("MainWindow", "移动部"))
        self.pushButton_jianyi.setText(_translate("MainWindow", "建议"))
        self.pushButton_setting.setText(_translate("MainWindow", "设置"))
        self.pushButton_tools.setText(_translate("MainWindow", "工具"))
        self.label_name.setText(_translate("MainWindow", "Yangtze University Computer Association"))
        self.pushButton_min.setToolTip(_translate("MainWindow", "最小化"))
        self.pushButton_close.setToolTip(_translate("MainWindow", "关闭"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "长大攻略"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "西区地图"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "校历"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "计协攻略"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "计协简介"))
        self.comboBox_1.setItemText(2, _translate("MainWindow", "实验部分"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "资源服务"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "资源整合"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "其他干货"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "号内搜索"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "免费福利"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "刷赞"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "办公部"))
        self.label_3.setText(_translate("MainWindow", "PS部"))
        self.label_4.setText(_translate("MainWindow", "剪映部"))
        self.label_5.setText(_translate("MainWindow", "硬件部"))
        self.label_6.setText(_translate("MainWindow", "新媒体部"))
        self.label_65.setText(_translate("MainWindow", "网站部"))
        self.label_7.setText(_translate("MainWindow", "编程部"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "新建项目"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("MainWindow", "移动部"))
        self.checkBox_ui.setText(_translate("MainWindow", "优化视觉UI"))
        self.pushButton_warning.setText(_translate("MainWindow", "提醒"))
        self.pushButton_loginweb.setText(_translate("MainWindow", "校园网"))
        self.label_user.setText(_translate("MainWindow", "User"))
        self.label_username.setText(_translate("MainWindow", "用户ID"))
        self.label_emailcode.setText(_translate("MainWindow", "邮箱地址"))
        self.label_userjob.setText(_translate("MainWindow", "Your Job"))
        self.label_QQ.setText(_translate("MainWindow", "QQ"))
        self.label_QQnum.setText(_translate("MainWindow", " "))
        self.label_phone.setText(_translate("MainWindow", "手机号"))
        self.label_phonenum.setText(_translate("MainWindow", " "))
        self.label_Email.setText(_translate("MainWindow", "邮箱"))
        self.label_Emailnum.setText(_translate("MainWindow", " "))
        self.label_Name.setText(_translate("MainWindow", "姓名"))
        self.label_Namenum.setText(_translate("MainWindow", " "))
        self.label_Code.setText(_translate("MainWindow", "学号"))
        self.label_Codenum.setText(_translate("MainWindow", " "))
        self.label_School.setText(_translate("MainWindow", "学院"))
        self.label_Schoolnum.setText(_translate("MainWindow", " "))
        self.label_zhu.setText(_translate("MainWindow", "信息来自到梦空间或QQ"))
        self.lineEdit_account.setPlaceholderText(_translate("MainWindow", "手机号"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "密码"))
        self.pushButton_login_2.setText(_translate("MainWindow", "登录"))
        self.pushButton_enrool.setText(_translate("MainWindow", "QQ登录"))
        self.pushButton_backlogin.setText(_translate("MainWindow", "到梦空间登录"))
        self.lineEdit_phone.setPlaceholderText(_translate("MainWindow", "QQ号"))
        self.pushButton_login.setText(_translate("MainWindow", "加入"))
        self.label_74.setText(_translate("MainWindow", "编程部部长"))
        self.pushButton_22.setText(_translate("MainWindow", "变更"))
from PyQt5 import QtWebEngineWidgets
